
# Generated by Django 2.0.5 on 2019-01-06 19:41
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('str_id', models.CharField(editable=False, max_length=58, null=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('speaker', models.CharField(blank=True, max_length=50, null=True)),
                ('speaker_image_url', models.URLField(blank=True, null=True)),
                ('speaker_website_url', models.URLField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('venue_name', models.CharField(blank=True, default=None, editable=False, max_length=500, null=True)),
                ('venue_url', models.CharField(blank=True, default=None, editable=False, max_length=500, null=True)),
                ('all_day', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
                ('event_type', models.CharField(choices=[('competitions', 'competitions'), ('networking', 'networking'), ('speaker', 'speaker'), ('others', 'others')], default='competitions', max_length=200)),
                ('updated', models.BooleanField(default=False)),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='venue.Venue')),
            ],
            options={
                'verbose_name': 'Event',

                'verbose_name_plural': 'Events',
                'ordering': ('-created_at',),

            },
        ),
    ]
