# Generated by Django 2.0.5 on 2018-12-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('str_id', models.CharField(editable=False, max_length=58, null=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('speaker', models.CharField(blank=True, max_length=50, null=True)),
                ('speaker_image_url', models.URLField(blank=True, null=True)),
                ('speaker_website_url', models.URLField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('all_day', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
                ('event_type', models.CharField(choices=[('Competitions', 'Competitions'), ('Networking', 'Networking'), ('Speaker', 'Speaker'), ('Others', 'Others')], default='Competitions', max_length=20)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ('-created_at',),
            },
        ),
    ]
