# Generated by Django 2.0.5 on 2019-01-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190112_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='day',
            field=models.CharField(choices=[('day1', 'day1'), ('day2', 'day2')], default='day1', max_length=200),
        ),
    ]
