# Generated by Django 2.0.5 on 2018-12-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0001_initial'),
        ('events', '0002_auto_20181227_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='venue',
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ManyToManyField(blank=True, null=True, to='venue.Venue'),
        ),
    ]
