# Generated by Django 2.0.5 on 2019-01-19 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20190116_1319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('start_time',), 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
    ]
