# Generated by Django 2.0.5 on 2018-12-27 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20181227_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='venue',
        ),
    ]
