# Generated by Django 2.0.5 on 2019-01-19 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20190119_1117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-start_time',), 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
    ]
