# Generated by Django 2.0.5 on 2018-12-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='updated',
            field=models.BooleanField(default=False),
        ),
    ]
