# Generated by Django 2.0.5 on 2019-01-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='venue_url',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
