# Generated by Django 2.0.5 on 2019-01-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_venue_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='venue_name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
