# Generated by Django 2.0.5 on 2019-01-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20190101_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='peoplegoing',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
