# Generated by Django 2.0.5 on 2019-01-05 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_peoplegoing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='peoplegoing',
            new_name='people_going',
        ),
    ]
