# Generated by Django 2.0.5 on 2019-01-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20190105_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='people_going',
            field=models.IntegerField(blank=True, default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue_name',
            field=models.CharField(blank=True, default=None, editable=False, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue_url',
            field=models.CharField(blank=True, default=None, editable=False, max_length=500, null=True),
        ),
    ]
