# Generated by Django 2.0.5 on 2019-01-05 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20190105_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='people_going',
        ),
    ]
