# Generated by Django 2.0.5 on 2019-01-06 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponsor',
            old_name='website_link',
            new_name='website',
        ),
    ]
