# Generated by Django 2.0.5 on 2018-10-17 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180708_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password_hash',
        ),
        migrations.RemoveField(
            model_name='user',
            name='secret_key',
        ),
        migrations.AddField(
            model_name='user',
            name='esummit_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profession',
            field=models.CharField(choices=[('student', 'student'), ('professional', 'professional'), ('entrepreneur', 'entrepreneur')], default='student', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
